Repository OpenModelica/OpenModelica, pull requests merged in 2019-12, with the labels that each got.

#549 [CRuntime] Add time specific logging
  OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp
  OMCompiler/SimulationRuntime/c/simulation/solver/perform_simulation.c.inc
  OMCompiler/SimulationRuntime/c/simulation_data.h
  OMCompiler/SimulationRuntime/c/util/omc_error.c
  OMCompiler/SimulationRuntime/c/util/omc_error.h
  OMCompiler/SimulationRuntime/c/util/simulation_options.c
  OMCompiler/SimulationRuntime/c/util/simulation_options.h
Labels: enhancement

#624 fix build on Mac OS
  OMCompiler/SimulationRuntime/OMSI/solver/CMakeLists.txt
Labels: CI/Build OSX

#628 [cppRuntime] start simulation asynchronly and Send solver settings vi…
  OMCompiler/Compiler/Template/CodegenCpp.tpl
  OMCompiler/Compiler/Template/SimCodeTV.mo
  OMCompiler/Compiler/Util/Flags.mo
  OMCompiler/Compiler/Util/FlagsUtil.mo
  OMCompiler/SimulationRuntime/cpp/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/Core/SimController/SimController.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimController/threading/Communicator.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimController/threading/ToZeroMQEvent.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimulationSettings/GlobalSettings.cpp
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimController/ISimController.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimController/threading/Communicator.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimController/threading/ToZeroMQEvent.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimulationSettings/GlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimulationSettings/IGlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/Include/FMU/FMUGlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/Include/FMU2/FMU2GlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/src/OMC.cpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/include/omcZeromqTask.h
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/include/zhelpers.hpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/src/omc.cpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/src/omcZeromqTask.cpp
Labels: CI/Build MINGW, CI/Build OSX

#289 Fix some compiler warnings
  OMCompiler/SimulationRuntime/c/meta/meta_modelica_data.h
  OMCompiler/SimulationRuntime/c/simulation/simulation_info_json.c
Labels: enhancement
