Repository OpenModelica/OpenModelica, pull requests merged in 2019-11, with the labels that each got.

#505 [cppRuntime] added application omcZeroMQ that links to omc c api lib…
  OMCompiler/.gitignore
  OMCompiler/SimulationRuntime/cpp/CMake/CheckCXX11.cmake
  OMCompiler/SimulationRuntime/cpp/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/Core/SimController/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/Makefile.in
  OMCompiler/SimulationRuntime/cpp/Makefile.omdev.mingw
  OMCompiler/SimulationRuntime/cpp/omcWrapper/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/readme.md
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/src/omc.cpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/src/zhelpers.hpp
Labels: CI/Build MINGW, CI/Build OSX

#302 Add support for parallel Jacobian evaluation
  OMCompiler/SimulationRuntime/c/Makefile.in
  OMCompiler/configure.ac
Labels: CI/Build MINGW, CI/Build OSX

#524 Improve handling and sanitization of quoted identifiers.
  .CI/compliance-newinst.failures
  .CI/compliance.failures
  OMCompiler/Compiler/SimCode/SimCodeUtil.mo
  OMCompiler/Compiler/Template/CodegenCFunctions.tpl
  OMCompiler/Compiler/Template/CodegenUtilSimulation.tpl
  OMCompiler/Compiler/Template/SimCodeTV.mo
  OMCompiler/Compiler/Util/System.mo
  OMCompiler/Compiler/runtime/System_omc.c
  OMCompiler/Compiler/runtime/systemimpl.c
Labels: enhancement

#390 Reuse constant parts of Jacobians
  OMCompiler/Compiler/BackEnd/HpcOmScheduler.mo
  OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo
  OMCompiler/Compiler/SimCode/SerializeModelInfo.mo
  OMCompiler/Compiler/SimCode/SimCode.mo
  OMCompiler/Compiler/SimCode/SimCodeUtil.mo
  OMCompiler/Compiler/Template/CodegenC.tpl
  OMCompiler/Compiler/Template/SimCodeTV.mo
  OMCompiler/Compiler/Util/Flags.mo
  OMCompiler/SimulationRuntime/c/linearization/linearize.cpp
  OMCompiler/SimulationRuntime/c/optimization/DataManagement/MoveData.c
  OMCompiler/SimulationRuntime/c/simulation/solver/dassl.c
  OMCompiler/SimulationRuntime/c/simulation/solver/kinsolSolver.c
  OMCompiler/SimulationRuntime/c/simulation/solver/linearSolverKlu.c
  OMCompiler/SimulationRuntime/c/simulation/solver/linearSolverLapack.c
  OMCompiler/SimulationRuntime/c/simulation/solver/nonlinearSolverHomotopy.c
  OMCompiler/SimulationRuntime/c/simulation/solver/nonlinearSolverHybrd.c
  OMCompiler/SimulationRuntime/c/simulation/solver/stateset.c
  OMCompiler/SimulationRuntime/c/simulation_data.h
  OMCompiler/SimulationRuntime/fmi/export/openmodelica/fmu2_model_interface.c.inc
  testsuite/Makefile
  testsuite/openmodelica/debugDumps/optdaedump.mos
  testsuite/openmodelica/debugDumps/symjacdump.mos
  testsuite/simulation/modelica/commonSubExp/cse1.mos
  testsuite/simulation/modelica/commonSubExp/cse3.mos
  testsuite/simulation/modelica/commonSubExp/cseFunctionCall8.mos
  testsuite/simulation/modelica/commonSubExp/wrapFunctionCalls11.mos
  testsuite/simulation/modelica/jacobian/Makefile
  testsuite/simulation/modelica/jacobian/reuseConstantPartsJac1.mos
Labels: enhancement

#527 [cppRuntime] fix for negate alias parameter
  OMCompiler/Compiler/Template/CodegenCpp.tpl
  OMCompiler/SimulationRuntime/cpp/Core/DataExchange/XmlPropertyReader.cpp
  OMCompiler/SimulationRuntime/cpp/Include/Core/DataExchange/HistoryImpl.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/DataExchange/IHistory.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/DataExchange/Policies/BufferReaderWriter.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/DataExchange/Policies/DefaultWriter.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/DataExchange/Policies/MatfileWriter.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/DataExchange/Policies/TextfileWriter.h
Labels: CI/Build MINGW, CI/Build OSX

#522 Build and run OMEdit testsuite
  .CI/common.groovy
  Jenkinsfile
  Makefile.in
  OMEdit/Makefile.omdev.mingw
  OMEdit/OMEditGUI/OMEditGUI.pro
  OMEdit/OMEditLIB/Makefile.omdev.mingw
  OMEdit/OMEditLIB/Makefile.unix.in
  OMEdit/OMEditLIB/OMEditLIB.pro
  OMEdit/Testsuite/BrowseElectricalAnalogBasic/Test.cpp
  OMEdit/Testsuite/BrowseMediaAirReferenceMoistAir/Test.cpp
  OMEdit/Testsuite/Common/Testsuite.pri
  OMEdit/Testsuite/Common/Util.h
  OMEdit/Testsuite/Makefile.omdev.mingw
  OMEdit/Testsuite/Makefile.unix.in
  OMEdit/Testsuite/RunOMEditTestsuite
Labels: CI/Build MINGW

#525 [cppRuntime] Added config flags to configure use of zeromq communicat…
  OMCompiler/Compiler/Template/CodegenCpp.tpl
  OMCompiler/Compiler/Template/SimCodeTV.mo
  OMCompiler/Compiler/Util/Flags.mo
  OMCompiler/SimulationRuntime/cpp/Core/ReduceDAE/com/ModelicaCompiler.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimController/FactoryExport.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimController/SimController.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimController/threading/Communicator.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimController/threading/SimulationThread.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimController/threading/ToZeroMQEvent.cpp
  OMCompiler/SimulationRuntime/cpp/Core/SimulationSettings/GlobalSettings.cpp
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimController/ISimController.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimController/threading/Communicator.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimController/threading/ToZeroMQEvent.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimulationSettings/GlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/Include/Core/SimulationSettings/IGlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/Include/FMU/FMUGlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/Include/FMU2/FMU2GlobalSettings.h
  OMCompiler/SimulationRuntime/cpp/Include/SimCoreFactory/OMCFactory/OMCFactory.h
  OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/include/OMC.h
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/src/OMC.cpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcZeroMQ/src/omc.cpp
Labels: CI/Build MINGW, CI/Build OSX

#544 [CRuntime] Fix segmentation fault for parallel symbolic Jacobians
  OMCompiler/SimulationRuntime/c/simulation/solver/dassl.c
  OMCompiler/SimulationRuntime/c/simulation/solver/ida_solver.c
  OMCompiler/SimulationRuntime/c/simulation/solver/jacobianSymbolical.c
  OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c
  testsuite/simulation/modelica/jacobian/reuseConstantPartsJac1.mos
Labels: bug

#534 Traverse exhaustively when inlining functions.
  OMCompiler/Compiler/Util/VarTransform.mo
Labels: bug, enhancement

#573 Handle spaces in installation path for cpp-runtime
  OMCompiler/Compiler/Template/CodegenCpp.tpl
  OMCompiler/Compiler/Template/CodegenFMUCpp.tpl
  OMCompiler/Compiler/scripts/Compile.bat
  OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp
Labels: CI/Build MINGW

#548 [CRuntime] Option to build with USE_PARJAC on Windows
  OMCompiler/SimulationRuntime/c/Makefile.omdev.mingw
Labels: CI/Build MINGW

#597 Handle the spaces in installation path and working directory
  OMCompiler/Compiler/Script/CevalScriptBackend.mo
  OMCompiler/Compiler/Template/CodegenCpp.tpl
  OMCompiler/Compiler/Template/CodegenFMUCpp.tpl
  OMCompiler/Compiler/scripts/Compile.bat
Labels: CI/Build MINGW
