Repository OpenModelica/OpenModelica, pull requests merged in 2019-06, with the labels that each got.

#260 do not set env.PATH via script as this impacts the entire pipeline
  .CI/common.groovy
  Jenkinsfile
Labels: CI/Build MINGW, CI/Build OSX

#265 allow Win/MinGW stage to run on all nodes labeled windows
  Jenkinsfile
Labels: CI/Build MINGW

#266 exit on error on the Win/MinGW pipeline
  .CI/common.groovy
Labels: CI/Build MINGW

#218 ISSUE-5435: Added the possibility of resetting OMEdit via the UI
  OMEdit/OMEdit/OMEditGUI/Options/OptionsDialog.cpp
  OMEdit/OMEdit/OMEditGUI/Options/OptionsDialog.h
Labels: enhancement

#286 Don't quote environment variable otherwise short names won't work
  OMCompiler/Compiler/Script/CevalScript.mo
Labels: CI/Build MINGW

#288 Fix ticket:5548
  OMCompiler/Compiler/Script/CevalScriptBackend.mo
  OMCompiler/Compiler/Script/Interactive.mo
  OMCompiler/Compiler/Script/InteractiveUtil.mo
  testsuite/openmodelica/interactive-API/Makefile
  testsuite/openmodelica/interactive-API/Ticket5548.mos
Labels: CI/Build MINGW, CI/Build OSX
