Repository OpenModelica/OpenModelica, pull requests merged in 2019-10, with the labels that each got.

#370 [codegen] Improved handling of records and record arrays in the codegen.
  OMCompiler/Compiler/BackEnd/BackendDAEOptimize.mo
  OMCompiler/Compiler/FFrontEnd/FBuiltin.mo
  OMCompiler/Compiler/FFrontEnd/FGraph.mo
  OMCompiler/Compiler/FFrontEnd/FNode.mo
  OMCompiler/Compiler/FrontEnd/CevalFunction.mo
  OMCompiler/Compiler/FrontEnd/DAE.mo
  OMCompiler/Compiler/FrontEnd/DAEUtil.mo
  OMCompiler/Compiler/FrontEnd/Expression.mo
  OMCompiler/Compiler/FrontEnd/Inline.mo
  OMCompiler/Compiler/FrontEnd/InnerOuter.mo
  OMCompiler/Compiler/FrontEnd/Inst.mo
  OMCompiler/Compiler/FrontEnd/InstBinding.mo
  OMCompiler/Compiler/FrontEnd/InstSection.mo
  OMCompiler/Compiler/FrontEnd/InstUtil.mo
  OMCompiler/Compiler/FrontEnd/InstVar.mo
  OMCompiler/Compiler/FrontEnd/Lookup.mo
  OMCompiler/Compiler/FrontEnd/Patternm.mo
  OMCompiler/Compiler/FrontEnd/SCodeUtil.mo
  OMCompiler/Compiler/FrontEnd/Static.mo
  OMCompiler/Compiler/FrontEnd/Types.mo
  OMCompiler/Compiler/FrontEnd/ValuesUtil.mo
  OMCompiler/Compiler/NFFrontEnd/NFConvertDAE.mo
  OMCompiler/Compiler/Script/CevalScriptBackend.mo
  OMCompiler/Compiler/Script/StaticScript.mo
  OMCompiler/Compiler/Script/SymbolTable.mo
  OMCompiler/Compiler/SimCode/SimCodeFunction.mo
  OMCompiler/Compiler/SimCode/SimCodeFunctionUtil.mo
  OMCompiler/Compiler/SimCode/SimCodeUtil.mo
  OMCompiler/Compiler/Template/CodegenAdevs.tpl
  OMCompiler/Compiler/Template/CodegenC.tpl
  OMCompiler/Compiler/Template/CodegenCFunctions.tpl
  OMCompiler/Compiler/Template/CodegenCSharp.tpl
  OMCompiler/Compiler/Template/CodegenCpp.tpl
  OMCompiler/Compiler/Template/CodegenCppCommon.tpl
  OMCompiler/Compiler/Template/CodegenFMU.tpl
  OMCompiler/Compiler/Template/CodegenSparseFMI.tpl
  OMCompiler/Compiler/Template/SimCodeTV.mo
  OMCompiler/Compiler/Util/Error.mo
  OMCompiler/Compiler/Util/List.mo
  OMCompiler/SimulationRuntime/c/openmodelica_types.h
  OMCompiler/SimulationRuntime/c/util/boolean_array.c
  OMCompiler/SimulationRuntime/c/util/generic_array.c
  OMCompiler/SimulationRuntime/c/util/generic_array.h
  OMCompiler/SimulationRuntime/c/util/integer_array.c
  OMCompiler/SimulationRuntime/c/util/real_array.c
  OMCompiler/SimulationRuntime/c/util/string_array.c
  testsuite/flattening/modelica/records/RecordNonPublic.mo
Labels: CI/Build MINGW, CI/Build OSX, enhancement

#474 replace libzmq dep with cppzmq dep
  OMCompiler/Makefile.common
Labels: CI/Build MINGW, CI/Build OSX

#488 [cppRuntime] moved omccapi library project in omcWrapper subfolder, a…
  OMCompiler/SimulationRuntime/cpp/CMakeLists-VS2019.txt
  OMCompiler/SimulationRuntime/cpp/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/Core/SimController/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/Makefile.in
  OMCompiler/SimulationRuntime/cpp/Makefile.omdev.mingw
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/include/OMC.h
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/include/OMCAPI.h
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/include/OMCFunctions.h
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/readme.md
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/src/OMC.cpp
  OMCompiler/SimulationRuntime/cpp/omcWrapper/omcCAPI/src/OMCTest.cpp
Labels: CI/Build MINGW, CI/Build OSX

#507 Added missing else case for DAE.Dump.dumpAnnotationStr
  OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo
  OMCompiler/Compiler/FrontEnd/DAEDump.mo
Labels: bug
