Repository OpenModelica/OpenModelica, pull requests merged in 2020-05, with the labels that each got.

#830 copy libcurl dll and dependencies to build/bin
  OMCompiler/Makefile.omdev.mingw
Labels: CI/Build MINGW

#834 better fix for ticket:#5933, link libcurl statically on mingw
  OMCompiler/Compiler/boot/Makefile.omdev.mingw
  OMCompiler/Compiler/runtime/om_curl.c
  OMCompiler/Makefile.omdev.mingw
Labels: CI/Build MINGW

#839 fix encryption builds
  OMCompiler/Compiler/boot/Makefile.omdev.mingw
  OMCompiler/Makefile.common
Labels: CI/Build MINGW

#851 Do not hardcode OPENMODELICAHOME in OMEdit
  OMCompiler/Compiler/runtime/settingsimpl.h
  OMEdit/OMEditGUI/OMEditGUI.unix.config.pri.in
  OMEdit/OMEditGUI/OMEditGUI.win.config.pri
  OMEdit/OMEditLIB/OMEditApplication.cpp
Labels: CI/Build MINGW, CI/Build OSX

#853 attempt to fix OMSICpp build on Ubuntu Focal 20.04 LTS
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/Modelica/CMakeLists.txt
Labels: CI/Build MINGW, CI/Build OSX

#862 fix MSVC use of getcwd, allocate path dynamically
  OMCompiler/SimulationRuntime/c/linearization/linearize.cpp
  OMCompiler/SimulationRuntime/c/util/omc_msvc.h
Labels: CI/Build MINGW

#869 ticket:5943 kill OPENMODELICAHOME from OMNotebook and OMShell
  OMNotebook/OMNotebook/OMNotebookGUI/OMNotebook.config.in
  OMNotebook/OMNotebook/OMNotebookGUI/OMNotebookGUI.pro
  OMNotebook/OMNotebook/OMNotebookGUI/cellapplication.cpp
  OMShell/OMShell/OMShellGUI/oms.cpp
Labels: CI/Build MINGW, CI/Build OSX

#871 Use a locale-independent strtod
  OMCompiler/Compiler/runtime/ptolemyio.cpp
  OMCompiler/SimulationRuntime/c/Makefile.common
  OMCompiler/SimulationRuntime/c/Makefile.objs
  OMCompiler/SimulationRuntime/c/meta/meta_modelica_builtin.c
  OMCompiler/SimulationRuntime/c/simulation/simulation_info_json.c
  OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp
  OMCompiler/SimulationRuntime/c/util/OldModelicaTables.c
  OMCompiler/SimulationRuntime/c/util/omc_numbers.c
  OMCompiler/SimulationRuntime/c/util/omc_numbers.h
  OMCompiler/SimulationRuntime/c/util/read_csv.c
  OMCompiler/SimulationRuntime/c/util/read_csv.cpp
  OMPlot/OMPlot/OMPlotGUI/PlotWindow.cpp
  testsuite/openmodelica/fmi/ModelExchange/2.0/testBug2764.mos
  testsuite/openmodelica/fmi/ModelExchange/2.0/testBug3049.mos
  testsuite/openmodelica/fmi/ModelExchange/2.0/testDisableDep.mos
  testsuite/openmodelica/fmi/ModelExchange/2.0/testDiscreteStructe.mos
Labels: CI/Build MINGW, CI/Build OSX

#876 fix for ticket:5954
  OMCompiler/Compiler/Util/Settings.mo
  OMCompiler/Compiler/runtime/om_curl.c
  OMCompiler/Compiler/runtime/settingsimpl.c
Labels: CI/Build MINGW, CI/Build OSX

#881 Fix ModelicaLibraryConfig_gcc.inc for newer CMake
  OMCompiler/SimulationRuntime/OMSICpp/CMakeLists.txt
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/Modelica/CMakeLists.txt
Labels: CI/Build OSX

#893 ticket:5954
  OMCompiler/Compiler/runtime/settingsimpl.c
Labels: CI/Build MINGW, CI/Build OSX

#908 [C-runtime] Adding CVODE
  OMCompiler/Compiler/Util/Autoconf.mo.omdev.mingw
  OMCompiler/SimulationRuntime/c/Makefile.common
  OMCompiler/SimulationRuntime/c/Makefile.objs
  OMCompiler/SimulationRuntime/c/simulation/solver/cvode_solver.c
  OMCompiler/SimulationRuntime/c/simulation/solver/cvode_solver.h
  OMCompiler/SimulationRuntime/c/simulation/solver/ida_solver.c
  OMCompiler/SimulationRuntime/c/simulation/solver/model_help.c
  OMCompiler/SimulationRuntime/c/simulation/solver/solver_main.c
  OMCompiler/SimulationRuntime/c/util/simulation_options.c
  OMCompiler/SimulationRuntime/c/util/simulation_options.h
  OMCompiler/configure.ac
  testsuite/simulation/modelica/solver/Makefile
  testsuite/simulation/modelica/solver/problem1-cvode.mos
  testsuite/simulation/modelica/solver/problem2-cvode.mos
  testsuite/simulation/modelica/solver/problem6-cvode.mos
Labels: CI/Build MINGW, CI/Build OSX, enhancement
