Repository OpenModelica/OpenModelica, pull requests merged in 2020-11, with the labels that each got.

#6885 Add new debug flag combineSubscripts
  OMCompiler/Compiler/NFFrontEnd/NFComponentRef.mo
  OMCompiler/Compiler/NFFrontEnd/NFFlatModel.mo
  OMCompiler/Compiler/NFFrontEnd/NFInst.mo
  OMCompiler/Compiler/NFFrontEnd/NFVariable.mo
  OMCompiler/Compiler/Util/Flags.mo
  OMCompiler/Compiler/Util/FlagsUtil.mo
  OMCompiler/Compiler/Util/List.mo
  testsuite/flattening/modelica/scodeinst/CombineSubscripts1.mo
  testsuite/flattening/modelica/scodeinst/CombineSubscripts2.mo
  testsuite/flattening/modelica/scodeinst/Makefile
Labels: New Instantiation

#6884 new needed dlls for OMEdit in the new OMDev
  Makefile.omdev.mingw
Labels: CI/Build MINGW

#6886 Remove parmodauto cleaning for now.
  OMCompiler/Makefile.common
Labels: CI/Build MINGW

#6891 fix dataReconciliation tests for windows
  OMCompiler/SimulationRuntime/c/dataReconciliation/dataReconciliation.cpp
Labels: CI/Build MINGW

#6938 Fix redeclaration of dimensions.
  OMCompiler/Compiler/NFFrontEnd/NFDimension.mo
  OMCompiler/Compiler/NFFrontEnd/NFInst.mo
  testsuite/flattening/modelica/scodeinst/Makefile
  testsuite/flattening/modelica/scodeinst/RedeclareDim1.mo
  testsuite/flattening/modelica/scodeinst/RedeclareDim2.mo
Labels: New Instantiation

#6933 Fix copying of sundials libraries
  OMCompiler/Makefile.common
  OMCompiler/SimulationRuntime/OMSI/solver/CMakeLists.txt
Labels: CI/Build CentOS
