Repository OpenModelica/OpenModelica, pull requests merged in 2020-08, with the labels that each got.

#6687 Issue #6078, OPENMODELICALIBRARY env.var overrides the Modelica path
  .CI/common.groovy
  OMCompiler/Compiler/FrontEnd/ModelicaBuiltin.mo
  OMCompiler/Compiler/NFFrontEnd/NFModelicaBuiltin.mo
  OMCompiler/Compiler/runtime/settingsimpl.c
Labels: CI/Build MINGW, CI/Build OSX

#6689 Issue #6078: ignore OPENMODELICALIBRARY when running the testsuite
  OMCompiler/Compiler/runtime/settingsimpl.c
Labels: CI/Build MINGW, CI/Build OSX

#6688 Use Euler for FMUs without states
  OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp
  OMCompiler/SimulationRuntime/fmi/export/openmodelica/fmu_read_flags.c.inc
Labels: FMI

#6691 Ticket 6058 CVODE FMI variable stuck
  OMCompiler/SimulationRuntime/c/simulation/solver/cvode_solver.c
Labels: FMI

#6698 more fixes for Ticket:5550 on 32bit
  OMCompiler/SimulationRuntime/c/openmodelica_types.h
Labels: CI/Build MINGW, CI/Build OSX

#6705 temporary use fmu generation for omsicpp simulation
  OMCompiler/Compiler/Script/CevalScriptBackend.mo
  OMCompiler/Compiler/SimCode/SerializeInitXML.mo
  OMCompiler/Compiler/SimCode/SerializeModelInfo.mo
  OMCompiler/Compiler/SimCode/SimCodeMain.mo
  OMCompiler/Compiler/SimCode/SimCodeUtil.mo
  OMCompiler/Compiler/Template/CodegenCFunctions.tpl
  OMCompiler/Compiler/Template/CodegenFMU.tpl
  OMCompiler/Compiler/Template/CodegenOMSICpp.tpl
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/System/OMSI/OMSUSystem.cpp
Labels: CI/Build MINGW

#6718 Enable separate compilation of Cpp runtime for FMI without omc
  OMCompiler/SimulationRuntime/cpp/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/Core/Modelica/CMakeLists.txt
Labels: CI/Build MINGW, CI/Build OSX
