Repository OpenModelica/OpenModelica, pull requests merged in 2020-10, with the labels that each got.

#6753 [omiscpp] handle abort calls from fmu's in omsicpp simulation, send e…
  OMCompiler/SimulationRuntime/OMSICpp/omsi/src/omsi.cpp
  OMCompiler/SimulationRuntime/OMSICpp/runtime/include/Core/SimController/threading/Communicator.h
  OMCompiler/SimulationRuntime/OMSICpp/runtime/include/Core/SimController/threading/INotify.h
  OMCompiler/SimulationRuntime/OMSICpp/runtime/include/Core/SimController/threading/ToZeroMQEvent.h
  OMCompiler/SimulationRuntime/OMSICpp/runtime/include/Core/System/OMSUSystem.h
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/SimController/SimController.cpp
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/SimController/threading/Communicator.cpp
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/SimController/threading/SimulationThread.cpp
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/SimController/threading/ToZeroMQEvent.cpp
Labels: CI/Build MINGW

#6803 Exclude constants from FMI modelDescription dependecies
  OMCompiler/Compiler/SimCode/SimCodeUtil.mo
Labels: FMI

#6809 Add debug symbols to FMUs and don't remove tmp files
  OMCompiler/Compiler/Script/CevalScriptBackend.mo
  OMCompiler/Compiler/Template/CodegenFMU.tpl
Labels: FMI

#6826 put back the build of old cpp runtime for msvc
  OMCompiler/Makefile.omdev.mingw
Labels: CI/Build MINGW

#6772 Add FMI test case for enumerations including omc and OMSimulator
  testsuite/omsimulator/Makefile
  testsuite/omsimulator/enumeration.mos
  testsuite/omsimulator/enumeration2.mos
Labels: OMSimulator

#6831 update OMSimulator API in omc
  OMCompiler/Compiler/FrontEnd/ModelicaBuiltin.mo
  OMCompiler/Compiler/NFFrontEnd/NFModelicaBuiltin.mo
  OMCompiler/Compiler/Script/CevalScriptOMSimulator.mo
  OMCompiler/Compiler/Util/OMSimulator.mo
  OMCompiler/Compiler/runtime/OMSimulator_omc.c
Labels: OMSimulator

#6840 Fix -d=-nfScalarize for multidimensional eqs
  OMCompiler/Compiler/NFFrontEnd/NFArrayConnections.mo
  OMCompiler/Compiler/NFFrontEnd/NFFlatten.mo
  testsuite/openmodelica/cppruntime/testVectorizedBlocks.mos
  testsuite/openmodelica/cppruntime/testVectorizedPowerSystem.mos
  testsuite/openmodelica/cppruntime/testVectorizedSolarSystem.mos
Labels: New Instantiation

#6841 Array connection improvements.
  OMCompiler/Compiler/NFFrontEnd/NFArrayConnections.mo
  OMCompiler/Compiler/NFFrontEnd/NFComponent.mo
  OMCompiler/Compiler/NFFrontEnd/NFFlatten.mo
  OMCompiler/Compiler/NFFrontEnd/NFSimplifyModel.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect1.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect2.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect3.mo
Labels: New Instantiation

#6845 Fix indexing in ArrayConnections.transMulti.
  OMCompiler/Compiler/NFFrontEnd/NFArrayConnections.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect3.mo
Labels: New Instantiation

#6824 Remove duplicate updateBoundParameter calls
  OMCompiler/SimulationRuntime/fmi/export/openmodelica/fmu2_model_interface.c.inc
Labels: FMI

#6848 Array connection improvements
  OMCompiler/Compiler/NFFrontEnd/NFArrayConnections.mo
  OMCompiler/Compiler/NFFrontEnd/NFExpression.mo
  OMCompiler/Compiler/NFFrontEnd/NFSimplifyExp.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect1.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect2.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect3.mo
Labels: New Instantiation

#6849 Fix unconnected flow and inside/outside.
  OMCompiler/Compiler/NFFrontEnd/NFArrayConnections.mo
  OMCompiler/Compiler/NFFrontEnd/NFConnector.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect1.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect2.mo
  testsuite/flattening/modelica/scodeinst/ArrayConnect3.mo
Labels: New Instantiation

#6872 more clang msys2/mingw build fixes #5307
  Makefile.omdev.mingw
  OMCompiler/Compiler/Main/Main.mo
  OMCompiler/Compiler/Util/Autoconf.mo.omdev.mingw
  OMCompiler/Compiler/boot/Makefile.omdev.mingw
  OMCompiler/Compiler/runtime/omc_config.h
  OMCompiler/Makefile.omsi.common
  OMCompiler/README-OMDev-MINGW.md
  OMCompiler/SimulationRuntime/OMSICpp/CMakeLists.txt
  OMCompiler/SimulationRuntime/OMSICpp/Makefile.omdev.mingw
  OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/CMakeLists.txt
  OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/include/OMC.h
  OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp
  OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcZeroMQ/CMakeLists.txt
  OMCompiler/SimulationRuntime/OMSICpp/runtime/include/Core/System/OMSUSystem.h
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/Modelica/CMakeLists.txt
  OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Core/System/OMSI/OMSUSystem.cpp
  OMCompiler/SimulationRuntime/cpp/CMakeLists.txt
  OMCompiler/SimulationRuntime/cpp/Core/Modelica/CMakeLists.txt
  OMEdit/OMEditLIB/Debugger/Attach/ProcessListModel.cpp
  OMEdit/OMEditLIB/Debugger/Parser/Makefile.lib.omdev.mingw
  OMEdit/OMEditLIB/Debugger/Parser/Makefile.omdev.mingw
Labels: CI/Build MINGW, CI/Build OSX

#6875 do not force CFLAGS (#5307)
  Makefile.omdev.mingw
  OMEdit/OMEditLIB/Debugger/Attach/ProcessListModel.cpp
Labels: CI/Build MINGW

#6825 Simulation paralleization support with parmodauto
  OMCompiler/.gitignore
  OMCompiler/Compiler/.cmake/meta_modelica_source_list.cmake
  OMCompiler/Compiler/FrontEnd/Expression.mo
  OMCompiler/Compiler/SimCode/SerializeTaskSystemInfo.mo
  OMCompiler/Compiler/SimCode/SimCodeFunctionUtil.mo
  OMCompiler/Compiler/SimCode/SimCodeMain.mo
  OMCompiler/Compiler/Template/CodegenC.tpl
  OMCompiler/Compiler/Template/Makefile.common
  OMCompiler/Compiler/Template/SimCodeTV.mo
  OMCompiler/Compiler/Template/TaskSystemDump.tpl
  OMCompiler/Compiler/Util/Flags.mo
  OMCompiler/Compiler/Util/FlagsUtil.mo
  OMCompiler/Compiler/boot/LoadCompilerSources.mos
  OMCompiler/Makefile.common
  OMCompiler/Makefile.in
  OMCompiler/Makefile.omdev.mingw
  OMCompiler/SimulationRuntime/CMakeLists.txt
  OMCompiler/SimulationRuntime/ParModelica/auto/CMakeLists.txt
  OMCompiler/SimulationRuntime/ParModelica/auto/Makefile.common
  OMCompiler/SimulationRuntime/ParModelica/auto/Makefile.in
  OMCompiler/SimulationRuntime/ParModelica/auto/Makefile.omdev.mingw
  OMCompiler/SimulationRuntime/ParModelica/auto/om_pm_equation.cpp
  OMCompiler/SimulationRuntime/ParModelica/auto/om_pm_equation.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/om_pm_interface.cpp
  OMCompiler/SimulationRuntime/ParModelica/auto/om_pm_interface.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/om_pm_model.cpp
  OMCompiler/SimulationRuntime/ParModelica/auto/om_pm_model.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_cluster_dynamic_scheduler.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_cluster_level_scheduler.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_cluster_system.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_clustering.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_dynamic_scheduler.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_graph_dump.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_graph_dump.inl
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_level_scheduler.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_level_scheduler.inl
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_load_xml.inl
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_posix_timer.cpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_task_system.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_task_system.inl
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_timer.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_utility.cpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_utility.hpp
  OMCompiler/SimulationRuntime/ParModelica/auto/pm_win_timer.cpp
  OMCompiler/SimulationRuntime/ParModelica/auto/test_task_graph.cpp
  OMCompiler/configure.ac
  testsuite/openmodelica/bootstrapping/LoadCompilerSources.mos
  testsuite/special/MatlabTranslator/LoadCompilerSources.mos
Labels: CI/Build MINGW, CI/Build OSX, enhancement
