Repository OpenModelica/OpenModelica, pull requests merged in 2021-01, with the labels that each got.

#7065 Expand complex package constants.
  OMCompiler/Compiler/NFFrontEnd/NFPackage.mo
  OMCompiler/Compiler/NFFrontEnd/NFVariable.mo
  testsuite/flattening/modelica/scodeinst/Makefile
  testsuite/flattening/modelica/scodeinst/PackageConstant3.mo
Labels: New Instantiation

#7066 Fix prefixing of record expressions
  OMCompiler/Compiler/NFFrontEnd/NFCeval.mo
  OMCompiler/Compiler/NFFrontEnd/NFClass.mo
Labels: New Instantiation

#7068 Sort local function components
  OMCompiler/Compiler/NFFrontEnd/NFComponentRef.mo
  OMCompiler/Compiler/NFFrontEnd/NFFunction.mo
  OMCompiler/Compiler/NFFrontEnd/NFInstNode.mo
  OMCompiler/Compiler/Util/Error.mo
  OMCompiler/Compiler/Util/UnorderedSet.mo
  testsuite/flattening/modelica/scodeinst/FunctionCompOrder1.mo
  testsuite/flattening/modelica/scodeinst/FunctionCompOrder2.mo
  testsuite/flattening/modelica/scodeinst/Makefile
Labels: New Instantiation

#7069 Handle --replaceHomotopy flag
  OMCompiler/Compiler/NFFrontEnd/NFBuiltinCall.mo
  OMCompiler/Compiler/NFFrontEnd/NFFunction.mo
  testsuite/flattening/modelica/others/Homotopy.mos
Labels: New Instantiation

#7078 Improve handling of package constants
  OMCompiler/Compiler/NFFrontEnd/NFExpression.mo
  OMCompiler/Compiler/NFFrontEnd/NFInst.mo
  OMCompiler/Compiler/NFFrontEnd/NFPackage.mo
  OMCompiler/Compiler/NFFrontEnd/NFVariable.mo
  OMCompiler/Compiler/Script/NFApi.mo
  testsuite/flattening/modelica/scodeinst/Makefile
  testsuite/flattening/modelica/scodeinst/PackageConstant3.mo
  testsuite/flattening/modelica/scodeinst/PackageConstant4.mo
Labels: New Instantiation

#7079 Make fmi2GetXXX great again
  OMCompiler/SimulationRuntime/fmi/export/openmodelica/fmu2_model_interface.c.inc
Labels: FMI

#7081 Connection improvements
  .CI/compliance-newinst.failures
  .CI/compliance.failures
  OMCompiler/Compiler/NFFrontEnd/NFConnection.mo
  OMCompiler/Compiler/NFFrontEnd/NFConnectionSets.mo
  OMCompiler/Compiler/NFFrontEnd/NFExpandableConnectors.mo
  OMCompiler/Compiler/NFFrontEnd/NFOCConnectionGraph.mo
  testsuite/flattening/modelica/scodeinst/ExpandableConnectorFlow2.mo
Labels: New Instantiation

#7098 Workaround for #7097
  OMCompiler/Compiler/NFFrontEnd/NFFlatten.mo
Labels: New Instantiation

#7071 Replace CI test for CentOS6 with CentOS7
  .CI/cache-centos7/Dockerfile
  .CI/common.groovy
  Jenkinsfile
Labels: CI/Build CentOS

#7101 Remove the instantiate button for SSP
  OMEdit/OMEditLIB/MainWindow.cpp
  OMEdit/OMEditLIB/MainWindow.h
  OMEdit/OMEditLIB/Modeling/LibraryTreeWidget.cpp
  OMEdit/OMEditLIB/Modeling/LibraryTreeWidget.h
  OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp
  OMEdit/OMEditLIB/OMS/OMSSimulationOutputWidget.cpp
  OMEdit/OMEditLIB/TLM/TLMCoSimulationOutputWidget.cpp
  OMEdit/OMEditLIB/Util/Helper.cpp
  OMEdit/OMEditLIB/Util/Helper.h
  doc/UsersGuide/source/omedit.rst
Labels: COMP/OMEdit, COMP/OMSimulator

#7107 Open both model and root system when creating a new SSP model
  OMEdit/OMEditLIB/OMS/ModelDialog.cpp
Labels: COMP/OMEdit, COMP/OMSimulator

#6787 Adding test case for OMSimulator with KINSOL solver
  testsuite/omsimulator/Makefile
  testsuite/omsimulator/testLoopsOverFMUs.mos
Labels: COMP/OMSimulator

#7116 Fix manually rerouting of connections (on WSL?)
  OMEdit/OMEditLIB/Annotations/ShapeAnnotation.cpp
Labels: COMP/OMEdit
